version: '3.4'

networks:
  cliniqueSysApp:

services:
  clinicdb:
    container_name: Database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 8002:1433
    environment: 
        - ACCEPT_EULA=Y
        - SA_PASSWORD=password-123@
    networks:
        - cliniqueSysApp
    volumes:
      - db_data:/var/lib/mysql

  clinic:
    container_name: clinique-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8081:80 
    depends_on:
        - clinicdb
    environment:
        - DB_HOST=http://172.16.1.70:8082
        - DB_NAME=cliniqueApp
        - DB_PASSWORD= password-123@
    networks:
        - cliniqueSysApp
volumes:
  db_data: 
