version: '3.4'

services:
  clinic:
    image: clinic 
    build:
      context: .
      dockerfile: Clinic/Dockerfile 
    ports:
      - "8089:8089"
    depends_on:
      - db
    

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clinique_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: 